version: '3'

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - proxynet
  backend:
    build:
      context: .
      dockerfile: 'packages/frontend/Dockerfile.dev'
    restart: unless-stopped
    ports:
      - "3002:3000"
    networks:
      - proxynet
    volumes:
      - './packages/backend:/app'
      - './packages/backend/node_modules:/app/node_modules'
    depends_on:
      - mongo
  frontend:
    build:
      context: .
      dockerfile: 'packages/frontend/Dockerfile.dev'
    restart: unless-stopped
    ports:
      - "8082:8080"
    networks:
      - proxynet
    volumes:
      - './packages/frontend:/app'
      - './packages/frontend/node_modules:/app/node_modules'
    depends_on:
      - backend

networks:
  proxynet:
    name: app_network
